#pragma once

//--------------------------------------------------------------------------------------------------
inline const char *give_art()
{
    return
        "                     ,    ..       ..,   ...  . .,, ,....  . **/...             \n"
        "             ..              .  .,,.. .. **... .... .,,,,,,,,,. ....    ..      \n"
        "         /..            . ....,...,, ,.,*..... ... . ,...,/*/,./**/*            \n"
        "        .*.   .   .    ......,.,*,**,,,*.....,*.,.,/.,.   .  ..... ..           \n"
        "    .  /,..     ....,.,*,,,/**//(/#((,,.*,/***/*,*,,**,, . ,.     ..      . .   \n"
        "      /,.     ......,*/(/*(((/##(//(((#(#((/#(*(((/**,,,..   .   ...,,       .. \n"
        "   . ,,    .,,..,,,/*////((#####(#(###########(((*#((//*,.,,...  . ,.,  .       \n"
        " ...,    . ..,,,*//*((###%##(###%%#%%%%#%((#%##(##/((((*//**,.,.. . .....       \n"
        " .....  ....,***(/(##%##%##%#%%%%(%#%%%%%#%#%######((#((//***..,.... ..,.,     .\n"
        "  ...*, .,,,/*/(/((#######%%%%%#%%%%%%%%%%%%%######%##(((/(*,*,,,,.  .  .**.    \n"
        "   .. ..,.*///((#(######%%%%%%%%%%%%%%%%%%%%%%%%%######((((/,,,*,,.,, .  .. *.. \n"
        "  .,.,.*,*.//(((#(##%#%%%%%%%%%%%%%%&&&%%%%%%%%%#####(#(((((/(,**,,..     .. /,.\n"
        "    .,,,///*//#(#(####%%%%%%%%%%%%%%%%%%%%%%%%%%%%%####(##((((((/,*....    .  ..\n"
        "    .,.,//((((((#####%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#######(((((((/*,, ..     ..\n"
        "    ...//(/(((((#####%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%#########((((((/**,....  .  \n"
        "    ..*/(((((#######%#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%###((######((((/**,.....  ..\n"
        "    .,/*(((((###(#####%%%%%%%%%%%%%%%%%%%%%%&%%%%#####(((#(#(##(((((/**,..... ..\n"
        " .  .,**((((((##########%#%#%%%%&%%&%%&&%%%##//*(/*/*/(,,,.,*,,*/(((/***,,......\n"
        ". . .,**((((///((/(/,*(//*#/(#(%%%%%%%%%%%####((/**///(**,**((*,,/((//***,......\n"
        " .  ,***//,,,,*/,,*,*,*(///((((####%%%%%###(#############(/((##(((((//***,......\n"
        " . ..*/*//((##((//(/(##############%%%%%%####(##################((((///**,,.....\n"
        "..*,.***//((############(####(####%#%%%###(##(#################(((((/(//**,,..,.\n"
        ".*/*.*////((((((######((#((/(#(######%#####(###########******/(##((((((/*,,,*,.,\n"
        ".....,//(((((((*////(##############%%%%%#########%%%%%%##########((((((/***///,,\n"
        ".,/./*//(((((########################%%%%####(#%%%%%#%%%###########((((//**////*\n"
        ".,.,///(((((########%%%#%%%%%%######%%##%##%%%%##%%%%#%%%##%%########(((/**/(//*\n"
        "..,,,*/((((#####%%%%%%%%%%%%%%##%#%%&%%#%%%%%%%%#%##%#%%%%%#%%#######(((//////*,\n"
        "...,/*/(((######%%%%%%%%%%%%%%%%%%%%%%%%%&&%%%%&%%%%##%%%%%%%##%#####((//////,*,\n"
        ".....**/((#####%%%%%%%%%%%%%%%%&&%%%%%%%&&%&&%%%&&%%%#%%%#%%#%%%%%%##((////****,\n"
        ".....,,//((#####%%%%%%%%%%%%%%%%&&%&%%&&&&&&&&&&&&&%%%%%%%%%%%%#%%###((//***,*,,\n"
        "......*,/((#####%%%%%%%%%%%%%%&%&&&%%&@&@&&&@&&&&&&&%%%%%%%%%%%%%%%##((//*,,.,..\n"
        "*..,,.,,,/((####%%#%%%%%%&%%%%%%&&@&&@@@@@@@@@@@&&&&%%%%%%%%%#######((//*,,*,,..\n"
        "...,,.,,*//(((####%%#%%#%%%%%%%&&&&&@@@@@@@@@@@@@@&&%&%%%####%#####(((//,****,,.\n"
        "..,.,,,,,*//((((#########%%%%%%%&&&&&&@@@@@@@@@@@&&%&&%%#%#%###(((((((////***, .\n"
        " ..,.,,,*/,/((((##(((########%%%&%&&&@&&@&&&@@@&@&@@%&%######%###(((/(//*//**,,.\n"
        "..,,,,******(((((###(#######%%%%%%%&%&&&&&&&&&&&&%%#&%%&&%####%###(((((/*//**...\n"
        "*/,.,,,..,,,/((((#####(((((####%%%%%&%&&&&&&&&%&&%#(%#((((###%#%#((((((//*/*,,..\n"
        "*.,,,,,.,,,,*/(((((###(#(##((#%###%%%%%%%%%%%#%%%#((%###%%#&#####((((/*****,,,..\n"
        ".,.,,...,,,*,*((((############((####(#%#%#####(#&(((((((%(######(##(/*,,,***,...\n"
        ".,..,...,,,.,*,/(((#######(#(#########%%#%%&%###((#(#((%((####%%#(((/,*..,/*,.. \n"
        ".,.....,,*,,/*,,*(((##############(##%%%%%%%%######((((/##%#%##%#((*//,,........\n"
        ".,...,,,,,.,,/,,.*/(((#%###########%#&%%%%%%%####%#((((###((##(##((/*,,,........\n"
        ",,,,,.,,,,**,,.,,,(*(####%########%###########%%%@##########((((/(/*,*..,,......\n";
}

//--------------------------------------------------------------------------------------------------
inline const char *give_art2()
{
    return
        "?JY5Y???J55Y55P555YY555YY5555P5555PPPPPPPPP55555PPPPP5PPPGPPGGGGGGGGGPGGGGGGGGGGGGGGGGGPPGGGGBBBGPP7\n"
        "5PP5555PPPGPPBBB5G##BGPGB##BGGGGGGGPGGGGGBBBBBBB###BBBB##BB###B##BB#BBBBBBBB##BBBB###BBBGBBGBBBBBGG7\n"
        "GP5JYJ5BPG##BG5PPPPG55GB#BGP5GB##BG5GGGPPPPGGGPGB#BBBB##BBB#BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBGG7\n"
        "PPJPG5JPP55B##BYBBBBBGGGGPPGGB#BGGPG###BBBPP#BGGP5GGBBBBBBB#BBBB####BBBBBBBBBBBBBBBBBBBBBBBGBBBBGGG7\n"
        "JGJJ55YBGJYP555?5GB#BBBBBGPGBBP5PGB#####BBG5GGPGBGYGGGGGGP5PGGBB##BB######BBBBBBBBBBBBBBBBBBBBBGBGG7\n"
        "?YJJYGYP5J5GPJ5BBGPGBBB##BBBGG5BB#####BBGPPBB#BBGG5PGBBBBBBPPBGGB#BBBB###BBBBBBBBBBBBBBBBBBBBBBBGGG?\n"
        "?7JYPJ?PB#BG5YPPBBBBGBBB##B##BPGBBB##B5PPG###GGBBPGBBB##B##GG#BBGB##BB####B###BBBBBBBBBBBBBBBBBBGGG?\n"
        "??YPYJJJJYJ5GGYYBBGGG5#BB##BBBBGPPPP5YPB###BPGBBGGB#BB##B#GPB#B#BP####BB#B###BBBBBBBBBBBBBBBBBBGGGG7\n"
        "5J?JPBBBGYG#BPYYJJPPJY5PGB##BBBBB#BB5PBB##BYPGPGBBBBBBB#BP5GBBBBBP##BBBBBBB##BBBBBBBBBBBBBBBBBGGGGG7\n"
        "!J?YYPGP5?5P5GGGGY5Y5#BPP5B#BBBBBBBBG55PPG55PGBBBBBBBBBG55PBGGGGP5BBB##BB#B##BBBBBBBBBBBBBBBBGGGGGG~\n"
        "5Y5#5?JYPGG?BBBGP5YYPBBBBGYBBBBBBBBBBBBBBGYB#BBBBBBPPP55GBB#BBBG5GBGGBBBB#B##B##BB#BBBBBBBBBBGBBGGG!\n"
        "5YJB#BBBBBB5YYY5GB#BYG#BBB?GBBBBBBBBBB#BBB55GBBBBPYY5PGBBBBBBBB5P#BBBPG####B####B#BBBBBBBBBBBBBBBBG7\n"
        "Y5?PGP5PGBBBGB###BPJY55PGYJBBBBBBBBBBBBBBBGPP555YYPGGBBBBBBBB#G5BBBBBBP######BB###BBBBBBBBBBBBBBBBB?\n"
        "YBGJYGBBBBBGPB#B5GGGGGY5YYBGGGBBBBBBBBBBBBBBBBGYGBB#BBBBBB###GYPBBBBBB5###BBBB##BBBBBBBBBBBBBBBBBBB7\n"
        "?PBP555Y5YYYPBBGYGGGP5?J?5BBBPGBBBBBBBBBBBBBBBP5#BBBBBBBBGGGP5GGGGGGBPPBBBBB##BBBBBBBBBBBBBBBBBBBBP~\n"
        "GGGYPBBGGGBB5PBBGPP5PPBBY5GGG5JGBBBBBBBBBBBBBBPYBBB#BBBGPGGPPBBBBB##BPB#BBB##BBBBBBBBBBBBBBBBBBBGG5^\n"
        "YGPY5BBGPPGG55BBBBBBBBBPJY5PP?PP5PBBBBBBBBBBBBBPY5PPPP5PPPGBBBBBB#BG5GGGBBB##BB#BB#BBBBBBBBBBBBGGGG!\n"
        "PGP55J555555YGBBBBBBBGYPGBGYYG#BBP5#BBBBBBBBBBBBBGG5PGGGBB#BBBBBG5YPBBBBBBPGBBBBBBBBBBBBBBBBBBGGGGG?\n"
        "GGGYYBBBBBBB55BBBBBBB5PBGP5?Y55B#BJB#BBBBBBBBBBBBBB5BBBBBBBBGPPPPPB##BBB#GGBGGBBBBBB#BBBBBBBBGGGGGGY\n"
        "GGP5P555PP5YYPPBBBBBBGG55GGGPYJ5G5JGGBBBBBBBBBBBBBBGBBBBBBB55PGGB###BBBBBP#B#PGBBBBBBBBBBBBBBBBGGP57\n"
        "BBG5GYPGGGGBBBGYBBBBB#BBBBB555JPPYBBGYBBBBBBBBBBBBBBGPPPP55GBB#BB#BBB#BP5GGGG5PPPBBBBBBBBBBBBBBGGGP7\n"
        "BBBBJYBBBBBGGGPYBBBBBBBBBB5PBG5YPJPB#YPBBBBBBBBBBBBBBBBBBPB###BBBBBBBG5GBBBBB5BBPYBBBBBBBBBBBBBBGGP?\n"
        "BBBBY55YYY5YY5YGBBBBBBBGBBGGPPPPYPBGGJB#BBBBBBBBBBBBBBBBB5BBBBBBGGGBGGBBBBBBPGBBBYB#BBBBBBBBBBBBGGP?\n"
        "PGBBGJYGBBBBBBGJBBBBBBBBBBBBBBGJY55JYPBBGBBBBBBBBBBBBBBBBPGBBBPPGBBBBBBBBBBPGBBBP5BBB#BBBBBBBBBBGGG?\n"
        "YPGGBJJYPPPPPPYYGBBBBBBBBBBBBGJGBGJJPGGBGPBBBGBBBBBBBBBBBBGGG5PGGBBBBBBBBPPPGGGPPGGGPPBBBBBBBBBGGGGJ\n"
        "BBBBBJ5GP5555PGBBGBBBBBB#BBBBGYPPGPPGPJGPJGGBGGBBBBBGGBBBBBBPGBBBBBBBGGG5PBBBBGPB#BBBB5GBBBBBBGGGGGJ\n"
        "GBBB5B5B#BBBBBBB#G5BBBBBBBBBBBBGBBBGPJ5PJ5PP5BGGBBBBGGGBBBBB5BBBBBGPPPPPBBBBBPGBBBBBB#G5BBBBBBBGGBGY\n"
        "GBB5B#BPGBBBBBGGBB?BBBBBBBBBBBBBBBPGPYJ55JGB5BBBBBBBBBBGGBBBBPPPPP55PGBBBBBGPBBBBB#BBBB5BBBBBBBGGGP7\n"
        "GBBYBBB5Y5Y5PPP5J?5BBBBBBBBBBBBBBPYGPPG5J5P5YGGGBBBBBBGGBBBBBBBGG5BBBBBBBBPGB##B###B##PP#BBBBBBGGGP!\n"
        "BBB5GGPGBBBGGPPP55JGBBB##B#BBGBBBBBBBPPPPP55BBBG5BBBBGGBBBBBBBBBBPBBBBBGPGB####BBBBBBG5B#BBBBBBGBBG!\n"
        "5GBGJ5B#BBBBBBBB#BJ5BBBBBBBBBBBBBBBBGJGGG5JPPYG#YP#BBGPP5YJJY5PGBGGBBGGGBBBBBBBGGGGGG5PPPGBBBGGGGGP7\n"
        "PBBB5PPBBBBBBBGGP5YP#BBBBBBBBBBBBBBBBGGGBGGGP?5GJYYY???JYPPGP5YYYYJY5GBBBBGGGGBBBBBGPB#BBYGBGGGGGPP7\n"
        "5GGG5GBGPPP55P55J5GP5BBBBBBBBBBBBBBBBBBBBBG5Y5GJ7J5P55BGP5YYYJJYY55PP5YYYPBBBBBBBGPPBB###GPBBGGGPPP7\n"
        "PBBBGPBBBP5PGGGGBBBBYGBBBBBBBBBBBBBBBBBBBBY5?7YG5?BPY7?JJJ5PPPPP5YYYJJ?YYJJPBBBGPGBBBBBBBGPBBGGGGGP7\n"
        "5BBGBGPG5PB##BGGPPP55BBBBBBBBBGBBGGGGGGBBBJ!5BBP!~7?YJPGB##BBBBBBB##GY5Y?!!?J5GBBBBBBBB#BPBBBBBGGGP7\n"
        "5GGGGGBPYGPP5YYYYY55JY5GBBBBBBGBBBBBBGGBG??BPJ77YPPYYBBG5GBBBBBBBBBBBGPGP5?!~?YPBBBBBBBBPPGGBBBBBGG?\n"
        "PBGBBBBYPGY5GGGGBBBBG55?BBBBBBBBBBBBP?GP!YP?75JGGG5Y5YG#PP#BBBBBBBBBBBBBBBBBY!7?JPPPGGG5PGGP5PBBGGP!\n"
        "YPGGBBBJY7PBBBGBGGGGBPY?BBGBBBGGGGBG755!PG!JBBGGGBBGGYPP5BBGP5J?JJ?JY5PGB#BBBGJ!7?GBBG5PBBBBGYGGGGP7\n"
        "?5GBBBBP7JBBP55555YYYY7YBBBGGGGBBBB?JG!PG7?BBBBBBB5GB5Y!?YY?YGGGGPPPP5YJ7YGGPGBBJ?7GPPGBBBBBBYGBGGG!\n"
        "5BGGBBBBJ?PY5PGBBBGPYJJ5YPBGGBBBBB57B?JGY!GBBBBBBGGGY7??J5PJY55YY555555PGY!?G###BJ~!BBBGGBBBBYGBBBG7\n"
        "YGGGGBBBG7YGGGPPP55PPPPPYJBBBBBBBB75P!GG~5BBBBBB#B57J5PPY?7?Y55PBBGGBBP5YJY57?GGGG7~5#BBBBBB55GGGGG7\n"
        "YBBBBB#B5PJPBBBBBB#G55Y?JYPPPBBBBG!P?7#5~BBBBB##B??GBY5Y??PPPPJ7????JYYJJJYJ?J!P##5~?BGGGBB55BBBGBG?\n"
        "5BBBBB#G5#B5YGBBBG5555Y5GBBBPYPBBG!G?7#J!#B####B7?BB#P!YGYY777?PGYPBBBGGP5YYJ!J75B5~!GBBGGPPPBBGGGG?\n"
        "5GBBBBBB5B##BPGPYYPGPGBBB#BB#G?BBB7GP!BJ~B#####J7BBBY^Y#J!7JJYJPP??Y?7Y555P5Y?!Y!5P~!GGPPGBBG5GGGGG7\n"
        "5GGGBBBBG5BB###Y5B##BB#BGP55P5YBB#JJB~GP^G####B!5#BP^JB?^YBGJ??77?555JY5555Y5Y7!YYP~7PGB#BBBGPBGGGGJ\n"
        "5GGBBB#BBG5GBBP5B##BBBPYY5PP5PPPBBB7GY!B!7####B~5B#?!#Y:Y#G!JPY?7JJJYY?JY555J?7!77Y~7##BBBBB5GBGGGG?\n"
        "5PGBBBBBBBBGG5YPGBBBGY5PGGGGB#BYGB#G7G!JP^5####!J#G~P#!7BB755YPPJ5YY5YYYJYP55?!~!JY75GGBBBB5GBBGPGG7\n"
        "GGBBBBBBBBBB#PGGPBGP5PBBBB##GPY5GGGGJ?P~YP^P###Y!BP^GB~J#Y55YBPJJ5JJ??JJJJYPPJ~~!Y7!PBB#BG5GBBBB5GG7\n"
        "PGBBBBBBBBBB#5G#BBPGB#BB#BP5JJGBB#BBB5?P!JJ^P###7JB!J#7?#5P?BYJYYJJ?JYJY5?JYYJ!~7!!GBBPPPPBBBBBB5GG!\n"
        "GBBBBBBBB#BBBB5PG5GBBBBBGJJ5PB#BBBGPP5Y7Y7!?~?B#B~?P7PP~PPPYPJ7GY??J55?J5J?5?77!!?PGPPPGBBGGGGGP5GG!\n"
        "GGGGBBBB##BBBBBBPYBGPPPYJPB##BPPGPPY5GBG77J!7!!5#G775YPY!Y5JYYYYPJJJJJYY??J?!!775#BBBBBGGGGGGPPPP5G?\n"
        "GGGBBBB###B##BBBP5BBB#B5GB#BP5PBGP5GBBB#BJ7J?777!5G57JYY7~777?YYY5YJYYYYYY?!7?5JBB###GGB#BBGPGBGPYG7\n"
        "GGGBBBBB###BBBBBB55GBBPGBBPY5GPPGBBBBBGPPG5??JJJ!!?J5Y????!~~~~7Y555YYJ?7!!7?55JPPB#BPBB#BGBBBBG55G7\n"
        "PGBBBBBBBBBBBBBBBBGPPPYGP55GBBBBBBBG55PGBBGPG5!JYJ?777?JJJ??7?7!!!!!!~~~!77YGPPBBGJBBGBB#BBBBGPY5GB!\n"
        "5PGBBBBBBBBBBBBBBBBBBB5G5GBBBBBBBB55GB##G55BBGJY5555YJ?~~!!777??7777?JYPPJGBGBBGPP?5GB#BPGBBGPGBGGB!\n"
        "PGBBBBBBBBBBBBBBB#BBBBG5G#BB#BBB#GP#BBG55GGGG5PB#BBBG5P5YYJJY55PPGGBBBBBBPB#G5PGG5PBG5#BGBBBBGGP55G!\n"
        "5GBBBBBBBB#BBBBBBBBBB#B5GGGBBBBBGPBGGPPBBPPG5GBBBBBGPGP####BGPBBBBB#BBBBBB#G5##G5GBBGYPB##BGGGPPGPP7\n"
        "PGBBBBBBBBBBBBBBBB#####PGBBBBBBBPGBB##BG5555BBBB#BGP#G5###BPGGBBBBGG##BBBB#GPGBGGPP5PB#YGBGGGBBBGGP7\n"
        "5GGBBBBBBBB####B########BGGBBB##GG#BBGP55PBB#BB##BGBGPB##BG#BG#####5B###B######5PBGGBG55GGP#BBGP55G~\n"
        "YGBBBBBBBBBBBBB########B###BBBGBGPGP5PG5###B#BB#BPPGG#BB#GBBPB####B5PGB##########BPPP5G#BGJ5PBBBB5G~\n"
        "5BBBBBBBBB##BB#######BB###B######BGGGBBPP###BBBGGGPG##B##GPG###BGG5GB#BG######B##PPBGGGGP5GGYGBB5PG~\n"
        "PBBBBBB#B################B#########BBBGGPPPPGGBB###GBBBBGPG####GPGB#B##P###########55GGGPG5JPP5YGGG~\n"
        "5BBBBBBBBBB######B#####BB##############B##BBGGBGGBBBBBGPGBGBBBBBP#####GG###########BBBPPBGPGBGYJPPB^\n"
        "!PGBBBBBBBB##BBB##B#B#BB###BB##BB##BBBBBBB##B##BBBBBB#BBBBBBBGBBGGBBGPG#GGGPBGPB#####55GGPPPYJYYJYP:\n"
        "?GGBBBB##############BB####BBBBB#BB##BBBBBBBBB##BBBBBBBBBBBBBBBBBGPPPPPGPGPPGG5GBGBP55PBBJYY5P5YJY5.\n";
}

//--------------------------------------------------------------------------------------------------
inline const wchar_t *give_art3()
{
    return
        L"▒▓▄▄▄▄▄▄▄▄▄▄▄▄▓▄▓▄▓▓▓▓▓▓▓▓▓▓▓ÅÅ╩╩╝░░░░░▀▒▒╩╩╩╩Å#@▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░\n"
        L"▐▓▓▓▓▓▀▒▀▓▓▓▓▓▓▓▓▓▓▓▓▀▀▀░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╙▀▀▀▓▓▓▓▓▓▓▓▓▓▓▓▓▀░▒░░▓▓▓▓▒\n"
        L"▐▓▓▓░▒░▒░▓▓▓▓▓▓▓▀▀░░░░░.░░░`░ ,╓╓╓╥╦╦╦╗▒@▒▒≡░░µ░░░░,░░─  ░.░.╙▀▀▓▓▓▓▓▌▒░▒░▓▓▓▓▓▒\n"
        L"▐▓▓┌░▒▒▄▓▓▓▓▀▀░░░░░░░░;╓╗B▒▒▒▒▒▒▒▒▒▒░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒h╥╖    ░░░░░▀▓▓▓▄▄▓▓▄▓▓▓▓▒\n"
        L"▐▓▓▄▄▓▓▓▓▓▀ ░░░░░░╥6▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▄▄▒▒╩▒▒▄▄▒▒▒▒▒▒▒▒▒▒▒░▒░░%≡╖. ░░░░░▀▓▓▓▓▓▓▓▓▓▌\n"
        L"▐▓▓▓▓▓▓▓░░░░░░╓@▒▒▒▒▒▒▒▒░▒▄████████▀░░ ▒░] ╙███████▓█▄░░░░░░░░░░N╖. ░░░░▓▓▓▓▓▓▓▌\n"
        L"▐▓▓▓▓▓▀░░░░░@▒░▒▒▒▒▒░▄████▓▒▓█████▌░ *=░*░░ └████▓▓▓██████▄▒░░░░▒▒▒N, ░░░▀▓▓▓▓▓▌\n"
        L"▒▓▓▓▀ ░░░g▒▒▒▒▒▒▒░▒╙░░░▀▀▀███████▓▓▌░░, ░,░░╫▓▓████████▓▓╢╢▒╣▒░░░░░▒░▒╖░░░`▓▓▓▓▌\n"
        L"░▓▓▀░░░╓▒▒▒▒▒▒▒▒▄█░Ö¿τ\\░░░░░▀████▌ ░,░æ░╜░ ░█████▓╢▓▓▓▓▓▓▓▓▓▓█▓░░░▒░▒░▒░░░░▀▓▓▌\n"
        L"▐▓▌░░░Æ▒▒▒▒▒░▒▒███░~░Σ░▐ ░░░░░░░▀██╖.░▒*░░░░▒██╢▓╣╢▓▓▓▓▓▓▓▓▓▓╣███▒░░░▒▒▒░N░─░█▓▌\n"
        L"▐█░░░╫▒▒░▒░▒▒▒█████▌*ⁿ╜░░░▄░y░░░  ▀█>═*]░░░░▓▒╣╢▓▓▓▓▓▓╣▓▓▓▓▓▓█████▒░▒▒▒▒▒▒B░ ░▓▌\n"
        L"▒▌░░░▒▒▒░▒▒▒░████████▄░░░░*╩░░░  ░░░╗░░░░░╓╫▓╣▓▓▓▓▓╬╣▓▓╢▓╣▓████████░▒▒░░▒▒░▌░░▐▌\n"
        L"▐░░░╢▒▒▒▒▒▒▒▒██████████▓▄▄░░░ ░ /░░░ ¥░` ╓░░╙▓▓▓▓▓▓▓▓╬▓████████████▌░▒▒▒▒▒▒▐░.░▌\n"
        L"▒░░░▒▒▒▒▒░▒▒▒███▀▄▄▓▓▓▓▓▓▓▓▓▓▓▓▄@⌐=,░▌▒cj▒░░░░▓╢╣▓╣╢▒▒╢╣╢╣╫▒▒▓██████▒░░░▒▒▒░░░░▌\n"
        L"░░░░▒▒▒▒▒░▒░░██▓▓▓▓▓▓▓▓▓▓▓▓▓█╣▓▓▓░░⌐*,░╫▌▒*╤╓j╣╣╣╣▓██▓▒╢╣▒╢╢╢╢╣╣▓███▒░░░▒▒░▒░░░▌\n"
        L"░▓░░╫▒▒▒▒░░░░╫@▓▓▓▓▓▓▓▓M▓▓▓█▓▓▓▓▓▓▒░░░░]▌░░░▄▒▒▓╫╢╣▓▒▓▓╢▒╣╣╢╢╢╢╢╫▒█▌▒▒░▒▒▒░▌ ░▐▌\n"
        L"▒▓▄░ ▒▒▒▒░░▒░░k▀▓▓▓▓▓▓▓▐▓▓▓▓▓▀▒▒╢▒▒▒▒▒░╢▓%▒░▒░▒▒▒╢╢╣╣╣▒╢▒╫╢╢╣╢╢╣╢▓▓░▒▒▒▒▒░╣░ ░▓▌\n"
        L"░▓▓░░░▒▒▒░░░░░░░▄▓▀▀▀═▓▓▄███▒▒▒▒▓▒▒▒▒▒▒██▒▒▒▒▒▒▒▒▒▒▒▓▒╣╢╫╢▒╣▓▓╣╣▓╣░░░░▒▒▒╝░ ░▐╢▒\n"
        L"░▓▓▓⌐░░╙▒▒░░░░░░░▀█████████▒▒▒▒▒╢▒░▒▒▒▒██▓▒▒▄▒▒▒▒▒▒▒███████████▓▒▒░░▒▒░▒░░ .▄▓▓▒\n"
        L"▒▓▓▓▓▄ `░╙▒░░░░░░░░▀██████▌▒▒▒▒▒▒╫▒▒▒╬████▓▒▒▒▒▒▒▒▒▒╣████████▀░▒░▒▒▒░▒░░   █▓▓▓▌\n"
        L"░▓▓▓▓▓▓.░  ╙Ñ░░░░░░░░░▀███▓▒╢▒▒▒▒▒▒▒██▀ ░███▒▒▒╫▒▒▒▒╢█████▀░▒▒░▒░░░╝░░░ ░▄▓▓▓▓▓▌\n"
        L"░▓▓▓▓▓▓▓▄    `╙╢▒░░░░░░░░▀▀▓▒░▒▒▒▒▓████▄▄████▓▒▒▒░▒▒██▀▀░░░░░░░g╝░░░░░ ▄▓▓▓▓▓▓▓▌\n"
        L"░▓▓▓▓▀▓▓▓▓▓▄    ░╙╨▒░░░░░░░░░░╙▀▀██████████████▀▀▀░░░░░░░░░░╝╜╙░    ▄▓▓▓▓▓▓▓▓▓▓▌\n"
        L"░▓▓▓▐▓▓▓▓▓▌▓▓▄▄─    ░░╜╨░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╝╜╙`      ▄▓▓▓▀▓▓ ▓▓▓▓▓▓▌\n"
        L"░▓▓Γ▓▓▓U▓▓▓▐▓▓▓▓▓▄░ ░░░░░░ `╙╙╙╨H░░░░░░░░░░▒▒▒▒▒Ñ╨╜╙         ,▄▓▓▓▓▓▓▓▀▓▓▓▓▓▓▓▓▌\n"
        L"░▓▓▌▀▀;/▓▓/▓▓▓▓▓▓▓╣▓▓▄▄, ░    ─    ░░░░               .  ;▄▓▓▓▓▓▓▓▓▌▄▓▓▓▓▓▓M▓▓▓▌\n"
        L"░▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▄▄▄;     ░░░.  ,.,░░░,▄▄▄▄▓▓▓▀▀▀▀▀▀▓▓▓▓▓▄▀▀▀▀▀▄▓▓▓▓▌\n"
        L"▒▒▒╜▒▀▀▀▀▀▀▒▀▀▒▀▀▀▒▒▀▀▀▀▀▀╜▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀H▒Æ▀▀▀▀▀RßRRNßßß╩▀▀▀▀▀▀▒\n";
}
